config/routes.rb
Rails.application.routes.draw do
  resources :attachments
  resources :subcategories
  resources :categories
  resources :categories
  resources :resumes
  root 'articles#index'
  devise_for :nutzers, :skip => [:sessions]
  as :nutzer do
    get 'login' => 'devise/sessions#new', :as => :new_nutzer_session
    post 'login' => 'devise/sessions#create', :as => :nutzer_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_nutzer_session
  end
  devise_for :admins, :skip => [:sessions, :registrations]
  as :admin do
    get 'tglogin' => 'devise/sessions#new', :as => :new_admin_session
    post 'tglogin' => 'devise/sessions#create', :as => :admin_session
    delete 'tglogout' => 'devise/sessions#destroy', :as => :destroy_admin_session
  end
  resources :articles
  resources :pictures
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: [:show, :edit, :update, :destroy]
  before_action :is_admin?

  # GET /subcategories
  # GET /subcategories.json
  def index
    @subcategories = Subcategory.all
  end

  # GET /subcategories/1
  # GET /subcategories/1.json
  def show
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
  end

  # GET /subcategories/1/edit
  def edit
  end

  # POST /subcategories
  # POST /subcategories.json
  def create
    @subcategory = Subcategory.new(subcategory_params)

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully created.' }
        format.json { render :show, status: :created, location: @subcategory }
      else
        format.html { render :new }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategories/1
  # PATCH/PUT /subcategories/1.json
  def update
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @subcategory }
      else
        format.html { render :edit }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1
  # DELETE /subcategories/1.json
  def destroy
    @subcategory.destroy
    respond_to do |format|
      format.html { redirect_to subcategories_url, notice: 'Subcategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcategory_params
      params.require(:subcategory).permit(:category_id, :left, :right)
    end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.erb
<%= form_for(@subcategory) do |f| %>
  <% if @subcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
      <% @subcategory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :left %><br>
    <%= f.text_field :left %>
  </div>
  <div class="field">
    <%= f.label :right %><br>
    <%= f.text_area :right %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subcategories/edit.html.erb
<h1>Editing Subcategory</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcategory %> |
<%= link_to 'Back', subcategories_path %>

app/views/subcategories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subcategories</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Left</th>
      <th>Right</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcategories.each do |subcategory| %>
      <tr>
        <td><%= subcategory.category.id %></td>
        <td><%= subcategory.left %></td>
        <td><%= simple_format(subcategory.right) %></td>
        <td><%= link_to 'Show', subcategory %></td>
        <td><%= link_to 'Edit', edit_subcategory_path(subcategory) %></td>
        <td><%= link_to 'Destroy', subcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcategory', new_subcategory_path %>

app/views/subcategories/new.html.erb
<h1>New Subcategory</h1>

<%= render 'form' %>

<%= link_to 'Back', subcategories_path %>

app/views/subcategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @subcategory.category %>
</p>

<p>
  <strong>Left:</strong>
  <%= @subcategory.left %>
</p>

<p>
  <strong>Right:</strong>
  <%= @subcategory.right %>
</p>

<%= link_to 'Edit', edit_subcategory_path(@subcategory) %> |
<%= link_to 'Back', subcategories_path %>