config/routes.rb
Rails.application.routes.draw do
  resources :attachments
  resources :subcategories
  resources :categories
  resources :categories
  resources :resumes
  root 'articles#index'
  devise_for :nutzers, :skip => [:sessions]
  as :nutzer do
    get 'login' => 'devise/sessions#new', :as => :new_nutzer_session
    post 'login' => 'devise/sessions#create', :as => :nutzer_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_nutzer_session
  end
  devise_for :admins, :skip => [:sessions, :registrations]
  as :admin do
    get 'tglogin' => 'devise/sessions#new', :as => :new_admin_session
    post 'tglogin' => 'devise/sessions#create', :as => :admin_session
    delete 'tglogout' => 'devise/sessions#destroy', :as => :destroy_admin_session
  end
  resources :articles
  resources :pictures
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :name, presence: true
  validates :content, presence: true
  before_save :text_edit
  has_and_belongs_to_many :attachments
  
  def text_edit
    add_img
    uml
    newline
  end
  
  def add_img
    self.content.gsub!(/<</, '<img src="/uploads/picture/image/')
    self.content.gsub!(/>>/, '/image.png" />')
  end
  
  def add_mailto
    email = self.content[/<mail.*mail>/]
    email.gsub!(/<mail/, '')
    email.gsub!(/mail>/, '')
    self.content.gsub!(/<mail.*mail>/, '<a href="mailto:' + email + '">' + email + '</a>')
  end
  
  def newline
    self.content.gsub!(/\n/, '<br />')
  end
  
  def uml
    [self.name, self.content].each do |param|
      param.gsub!(/,,a/, 'ä')
      param.gsub!(/,,A/, 'Ä')
      param.gsub!(/,,o/, 'ö')
      param.gsub!(/,,O/, 'Ö')
      param.gsub!(/,,u/, 'ü')
      param.gsub!(/,,U/, 'Ü')
      param.gsub!(/,,s/, 'ß')
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :remove_html, only: [:edit]
  before_action :authenticate_admin!, except: [:index]
  
  def index
    if current_nutzer
      @articles = Article.all.where(name: current_nutzer.email)
    end
    if current_admin
      @articles = Article.all
    end
  end
  
  def new
    @article = Article.new
    @pictures = Picture.all
    @anhaenge = Attachment.all
  end
  
  def create
    @anhaenge = Attachment.all
    @pictures = Picture.all
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render action: :new, id: @article.id
    end
  end
  
  def edit
    @anhaenge = Attachment.all
    #@pictures = Picture.all
  end
  
  def update
    @anhaenge = Attachment.all
    @article = Article.find(params[:id])
    if @article.update_attributes(article_params)
      redirect_to articles_path
    else
      render action: :edit, id: @article.id
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.delete
    redirect_to articles_path
  end
  
private
  def article_params
    params.require(:article).permit(:name, :content, :resume, :anhaenge, :hauptanhang)
  end
  
  def remove_html
    @article = Article.find(params[:id])
    @article.content.gsub!(/<br \/>/, '')
  end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <div class="error_wrapper">
    Article could not be saved for the following <%= "reason".pluralize(@article.errors.count)%>: <br />
    <% @article.errors.full_messages.each do |message| %>
      - <%= message %> <br />
    <% end %>
  </div>
<% end %>
<br />
<h4>Anhänge</h4>
<table class="anhang_table">
	<tr>
		<td>ID</td>
		<td>Name</td>
	</tr>
	<% @anhaenge.each do |anhang| %>
		<tr>
			<td><%= anhang.id %></td>
			<td><%= anhang.name %></td>
		</tr>
	<% end %>
</table>

<%= form_for(@article) do |f| %>    
  <%= f.text_field :name, placeholder: "Titel", class: "input_field" %><br />
  <br />
  <%= f.text_field :resume, placeholder: "Resume", class: "input_field" %><br />
  <br />
  <%= f.text_field :anhaenge, placeholder: "Anhänge (durch Komma ohne Leerzeichen trennen)", class: "input_field" %><br />
  <br />
  <%= f.text_field :hauptanhang, placeholder: "Hauptanhang", class: "input_field" %><br />
  <br />
  <%= f.text_area :content, class: "input_field area_field" %> <br />
  <br />
  <%= button_tag "Zurück zum Blog", :type => 'button', :class => "button button_secondary", :onclick => "location.href = '#{root_path()}'" %>
  <%= f.submit "Artikel senden", class: "button button_primary" %>
<% end %>

app/views/articles/_pictures.html.erb
<section class="pictures">
  <h2>Alle Bilder</h2>
  <% if @pictures.count == 0 %>
    Du hast noch keine Bilder hochgeladen. <br />
    <br />
  <% end %>
  <%= button_to "Bilder hochladen", pictures_path, method: :get, :class => "button button_primary", form: {target: "_blank"} %>
  
  <div class="img_wrapper">
  <% @pictures.order("created_at desc").take(40).each do |picture| %>
    <div class="img_border">
      <%= picture.id %> <br />
      <%= image_tag picture.image_url, class: 'thumb' %> <br />
    </div>
  <% end %>
  </div>
</section>    

app/views/articles/edit.html.erb
<section class="article_form">
  <div class="content_wrapper">
    <h2>Artikel bearbeiten</h2>
    <%= render 'form'%>
  </div>
  <% if false %>
  <div class="content_wrapper">
    <%= render 'pictures'%>
  </div>
  <% end %>
</section>

app/views/articles/index.html.erb
<% if current_admin %>
  <%= render 'layouts/admin'%>
<% end %>
<% if current_nutzer %>
	<div class="button_wrapper">
	<%= button_to("Logout", destroy_nutzer_session_path, method: :delete, class: "button button_primary logout_button") %>
	</div>
	<br />
<% else %>
	<section id="header">
	  <div class="content_wrapper">
	    <h2>Tobias Grunwald</h2>
	    <%= image_tag('me', id: 'img_me') %>
	    <p>Sehr geehrte Damen und Herren,</p>
	    <p>ich habe mit der Entwickung dieses Internetauftritts bereits während meinem Auslandsaufenthalt in Australien begonnen. Mir war bereits zu dieser Zeit bewusst, dass ich mich, nach meiner Rückkehr nach Deutschland, stärker im Bereich Webdevelopment betätigen möchte. Die Entwicklung diente dementsprechend einerseits zur Verbesserung meiner Kenntnisse, hat jedoch andererseits auch den praktischen Nutzen, Ihnen nun meine Bewerbungsunterlagen und gleichzeitig einen Einblick in meine Arbeit zu übermitteln. </p>
	    <p>Bitte melden Sie sich mit den Ihnen übermittelten Anmeldedaten an, um diese einzusehen:</p>
	    <div class="button_wrapper">
	      <%= button_to("Zum Login", nutzer_session_path, method: :get, class: "button button_primary button_login") %>
	    </div>
	    
	  </div>
	</section>
<% end %>
<% if current_nutzer || current_admin %>
	<section id="articles">
	  <% @articles.order("created_at desc").each do |article| %>
	    <div class="content_wrapper">
	      <h2> Bewerbungsunterlagen </h2> <br />
	      <% if current_admin %>
	      <h4><%= article.name %></h4>
	      
	        <div class="button_wrapper content_menu_wrapper">
	          <%= button_to "Bearbeiten", edit_article_path(article), method: :get, class:"button button_edit" %>
	          <%= button_to "Löschen", article_path(article), data: {confirm: 'Sicher, dass du diesen Artikel löschen möchtest?'}, method: :delete, class:"button button_delete" %>

	        </div>
	        
	      <% end %>
	      <div class="button_wrapper content_menu_wrapper">
	      	<div id="resume_button" class="button button_secondary">Lebenslauf</div>
	      	<p></p>
	      	<div id="motivation_button" class="button button_primary">Anschreiben</div>
	      	<p></p>
	      	<div id="attachment_button" class="button button_primary">Anhang</div>
          </div>
          <br>
          <div id="bewerbung">
		      <div id="motivation_div">
		      	<h3>Anschreiben</h3>
		      	<%= sanitize article.content %>
	      	  </div>
	 	      
	 	      <div id="resume_div">
	 	      	<h3>Lebenslauf</h3>
	 	      	<% @resume = Resume.find(article.resume) %>
	 	      	<%= render "resumes/show" %>
	 	      </div>
	 	      
	 	      <div id="attachment_div">
	 	      	<h3>Anhang</h3>
	 	      	Hier finden Sie den Anhang zu meiner Bewerbung:<br />
	 	      	<% @attachments = article.anhaenge.split(",") %>
	 	      	<ul>
		 	      	<% @attachments.each do |attachment| %>
		 	      		<li><%= link_to Attachment.find(attachment).name, Attachment.find(attachment).link, target: :_blank  %> </li><br />
		 	      	<% end %>
	 	      	</ul>
	 	      	<br \>
	 	      	<% if article.hauptanhang %>
	 	      	Zudem finden Sie hier die gesamte Bewerbung, klassisch als PDF-Datei, für Ihre Unterlagen zusammengefasst:<br />
	 	      	<ul><li><%= link_to Attachment.find(article.hauptanhang).name, Attachment.find(article.hauptanhang).link, target: :_blank  %> </li></ul><br />
	 	      	<% end %>
	 	      </div>
 	        </div>
	    </div>
	  <% end %>
	</section>
<% end %>

app/views/articles/new.html.erb
<section class="article_form">
  <div class="content_wrapper">
    <h2>Neuer Artikel</h2>
    <%= render 'form'%>
  </div>
  <% if false %>
  <div class="content_wrapper">
    <%= render 'pictures'%>
  </div>
  <% end %>
</section>